### ISSUE TITLE
documentation does not mention need for scopes

### ISSUE THREAD

**Issue by mtoupsUNO** [autolab/autolab-cli#14]
In `README.md` the **Getting Client Credentials** section mentioned that we need to register a new API application. The text mentioned what we should use in the **Redirect URI** field. But it does not mention what to do with the **Scopes** field, and apparently that is important.

In the rails app I dug around and found the scopes defined in `config/initializers/doorkeeper.rb` and with some trial and error discovered that these values in the scopes field seem to be sufficient for the autolab-cli to function:

`user_info user_courses user_scores user_submit`

Is this correct? If so, I suggest updating `README.md` for the benefit of future users.

**Comment by TheodorJ** [comment]
ACK, I added the scopes to README.md and submitted a pull request. #16
