### ISSUE TITLE
[Autolab Status] Change max submissions to unpenalized submissions 

### ISSUE THREAD

**Issue by victorhuangwq** [autolab/autolab-cli#19]
autolab status

Due: Sat Jul 25 21:00:00 2020
Max submissions: Infinite
Max grace days: 1
It shows "Max submissions: Infinite". This is extremely misleading to students.
Could you change the output to display the number of unpenalized submissions.
In this case, it should display "Unpenalized submissions left: 9".

**Comment by damianhxy** [comment]
Addressed in #24
