### ISSUE TITLE
When Task does not have associated feedback, CLI reports and error instead of looking for tasks with associated feedback

### ISSUE THREAD

**Issue by victorhuangwq** [autolab/autolab-cli#22]
When the first task does not have associated feedback, the CLI reports an error instead of looking for the feedback of tasks that do have associated feedback.  See screenshot.

Here "--" for task 1 is normal because this task will be graded after the submission deadline.

**Screenshot:**
![image](https://user-images.githubusercontent.com/5773562/109900229-01487900-7c65-11eb-95f8-57463b16d719.png)

**Comment by oliverli** [comment]
Fixed in PR
