### ISSUE TITLE
autolab setup not properly setting up authorized clients

### ISSUE THREAD

**Issue by dpaceoffice** [autolab/autolab-cli#25]
When using 
```autolab setup```

Authorization shows as received, and that the user setup is complete.
However, when using ```autolab status```, the client reports that no user is setup. Looking at the web ui, no authorized applications are displayed. 

Currently running autolab version 2.8.0

**Comment by 20wildmanj** [comment]
Thanks for the issue submission, we'll take a look at this.

**Comment by 20wildmanj** [comment]
Hello,

If you're still encountering this issue, could you please try setting up your account again with `autolab setup -f` (to force a re-authorization), and then attach screenshots of the terminal output of the authorization flow? After completing the authorization flow, could you also try running `autolab courses`?

**Comment by damianhxy** [comment]
Closing as stale
