### ISSUE TITLE
Invalid subcommands return "Authorization invalid" error

### ISSUE THREAD

**Issue by TheodorJ** [autolab/autolab-cli#3]
I tried running "autolab course" (forgetting the 's' in "courses") and received the following error:

[ContextManager] tokens loaded
fatal: Cannot start autolab client
Authorization invalid or expired.

Please re-authorize this client by running 'autolab-setup'

This works when running any subcommand that isn't valid. It's not disastrous, but it is misleading.

**Comment by zyx-billy** [comment]
Is this still happening? I tried it on the latest master and the error is "Unrecognized command: course". Perhaps this was something that happened halfway through refactoring?

**Comment by TheodorJ** [comment]
It's still happening to me -- Could it maybe be because I'm running in debug mode?

**Comment by zyx-billy** [comment]
seems to be fixed in #4
